### ISSUE TITLE
cheerio.default is undefined in newest release

### ISSUE THREAD

**Issue by AlexanderPico** [neocotic/convert-svg#109]
After a couple years of working just fine, we're now seeing this error when attempting svg-to-png conversions...

```
TypeError: Cannot read properties of undefined (reading 'html')
    at [convert] (/home/runner/work/wikipathways-database/wikipathways-database/wikipathways-database/scripts/generate-svgs/node_modules/convert-svg-core/src/Converter.js:264:33)
```
https://github.com/neocotic/convert-svg/blob/main/packages/convert-svg-core/src/Converter.js#L264
That line is...

```
const svg = cheerio.default.html(this[_sanitize](cheerio.load(input, null, false)('svg:first'), options));
```

Why would `cheerio.default` be `undefined` suddenly?

**Comment by AlexanderPico** [comment]
Might be related to breaking changes in cheerio: https://github.com/cheeriojs/cheerio/releases. But convert-svg-core specifies `v1.0.0-rc.12`, so the release from 3 days ago shouldn't matter, right?

**Comment by AlexanderPico** [comment]
Indeed, the `cheerio.default.html` line works fine in `v1.0.0-rc.11`, but breaks with the new release of cheerio `v.1.0.0`. The older rc version is [already specified](https://github.com/neocotic/convert-svg/blob/main/packages/convert-svg-core/package.json#L39), but is being ignored or overridden?

Is it because of the rc syntax... or does it need to be in `overrides`?

**Comment by AlexanderPico** [comment]
Ah, apparently other packages depending on cheerio have suffered the same issue. The solution may indeed to be to force an override... https://github.com/cheeriojs/cheerio/issues/3993

**Comment by AlexanderPico** [comment]
Adding this to my package.json seemed to fix the issue:

```

  "pnpm": {
    "overrides": {
      "cheerio": "1.0.0-rc.11"
    }
```

**Comment by DrRefactor** [comment]
should this really be closed? Instead of hardcoding cheerio version resolution in projects, it should be hardcoded inside this lib.
