### ISSUE TITLE
Adding fonts

### ISSUE THREAD

**Issue by Felwin** [neocotic/convert-svg#38]
I know I can include fonts inside SVG but what if I prefer to install the fonts ? How can I do that ?
Do I need to install the fonts on the system ? on chromium ? inside the module ?

Thank you for your help

**Comment by jdelibas** [comment]
you can cheat a little and load the fonts like so

```svg
<svg>
    <defs>
      <style type="text/css">
      @import url('https://fonts.googleapis.com/css?family=Roboto');
      </style>
    </defs>
</svg>
```

Just need to be able to point to the font from the svg, you could also install them on the system and access them directly.

**Comment by neocotic** [comment]
Sorry for the super late response, but I feel that this is out of scope for this library. All packages support standard SVG rendering, exactly as it would appear in a Chrome browser. This means that anything that would apply to getting it to work in the browser, also applies here.

If you have any specific issues with a `convert-svg-to-*` package not using a font that you feel it should be, please raise a separate bug for that and it can be investigated, as that could be something specific to this tool.
