### ISSUE TITLE
SVG path to PNG

### ISSUE THREAD

**Issue by kszmigiel** [neocotic/convert-svg#50]
Hey,
I'm getting some SVG path string from a user. How can I convert it to PNG using this package? How should it be formatted?

**Comment by neocotic** [comment]
@kszmigiel Sorry for the super late response, but take a look at the [convert-svg-to-png](https://github.com/neocotic/convert-svg/tree/master/packages/convert-svg-to-png) documentation. There's plenty of examples in there but the simplest is to just call `convert(str)` and you'll have your PNG buffer.
