### ISSUE TITLE
Intermittent strange png result

### ISSUE THREAD

**Issue by 70ray** [neocotic/convert-svg#57]
Using this svg file 
[ba585957575f9f4b5b190bbd92b13b9c.zip](https://github.com/neocotic/convert-svg/files/2824360/ba585957575f9f4b5b190bbd92b13b9c.zip)
I sometimes get a good png (better than any other converter I can find) (after the fix to allow 'pt' units)
but sometimes I get this:
![bad](https://user-images.githubusercontent.com/31585092/52163761-aab38e00-26de-11e9-9e05-26b80bbe525e.png)

**Comment by 70ray** [comment]
Since this is intermittent it could work differently on other machines. Any suggestions to help track it down would be welcome.

**Comment by neocotic** [comment]
I'm sorry for the incredibly long delay in replying in responding to you but life sometimes gets in the way of OSS development. I thank you for your patience and, although I'm closing this issue out, you may want to try using today's [0.6.0](https://github.com/neocotic/convert-svg/releases/tag/0.6.0) release which includes your `pt` unit support etc. There's a chance the upgrade to the latest version of Puppeteer may have fixed some bugs relating to inconsistency.

If you continue to have this problem, please raise a new ticket with an SVG to reproduce the problem and, where possible, an expected and actual file of the output. I hope you can understand my delay.
