### ISSUE TITLE
Output Filename

### ISSUE THREAD

**Issue by Slexom** [neocotic/convert-svg#62]
Is possible, using cli, to add on the output filename some value?
An example:
I've an SVG called image.svg. I want convert it in different sizes png 512x512, 256x256 and so on. I want my output file to have as name image@512.png, image@256.png and so on. 
This is what I'm actually doing:

```
  "scripts": {
    "convert_512": "convert-svg-to-png --width 512 --height 512 --filename *@512.png ./*.svg",
    "convert_256": "convert-svg-to-png --width 256 --height 256 --filename *@256.png ./*.svg",
...
```

**Comment by neocotic** [comment]
Sorry for taking so long to get back to you. There's currently 2 ways of converting files as quoted from the README:

> * Pass SVG files to be converted to PNG files as command arguments
>   * A [glob](https://www.npmjs.com/package/glob) pattern can be passed
>   * Each converted SVG file will result in a corresponding PNG with the same base file name (e.g.
>     `image.svg -> image.png`)
> * Pipe SVG buffer to be converted to PNG to command via STDIN
>   * If the `--filename` option is passed, the PNG will be written to a file resolved using its value
>   * Otherwise, the PNG will be streamed to STDOUT

This means that you could use the second approach and simply pipe in the SVG data via `cat` or something. You just need to drop the `./*.svg` part as this is resulting in the first approach being followed, thus ignoring the `--filename` option.
