### ISSUE TITLE
Special characters outputs extra characters

### ISSUE THREAD

**Issue by Sciguymjm** [neocotic/convert-svg#64]
Using special characters such as &copy; in the SVG strings yields extra characters:

![Screen Shot 2019-07-31 at 2 46 42 PM](https://user-images.githubusercontent.com/1396015/62250593-221e5d80-b3a2-11e9-99ee-6f0b37dced4f.png)

This is what it looks like in Chrome:
![Screen Shot 2019-07-31 at 2 47 01 PM](https://user-images.githubusercontent.com/1396015/62250594-221e5d80-b3a2-11e9-886d-bbd5c2a1ad05.png)

**Comment by Fahme** [comment]
#63 created a quick fix for that check it out.

**Comment by neocotic** [comment]
I'm sorry for the incredibly long delay in replying in responding to you but life sometimes gets in the way of OSS development. I thank you for your patience and, although I'm closing this issue out, I hope you'll be glad to know that I believe this issue has been resolved in with today's [0.6.0](https://github.com/neocotic/convert-svg/releases/tag/0.6.0) release with the introduction of UTF-8 support.

If you continue to have this problem, please raise a new ticket with an SVG to reproduce the problem and, where possible, an expected and actual file of the output. I hope you can understand my delay.
