### ISSUE TITLE
convert-svg-to-jpeg 生成的图片无法使用windows图片浏览器打开

### ISSUE THREAD

**Issue by wow6haka** [neocotic/convert-svg#68]
convert-svg-to-jpeg 生成的图片无法使用windows图片浏览器打开，提示内存不足，不过肯定不是内存不足，图片仅有几十K，我的内存还有几个G呢。但是它可以在缩略图中显示，这很奇怪。
![111](https://user-images.githubusercontent.com/24407580/71046926-d44d9a80-2174-11ea-8471-0bbfc0f84eb7.png)

**Comment by neocotic** [comment]
This is not something that I've experienced before but I tend to use Linux over Windows. Does this happen for all images you convert or just some and does this happen with any other pictures on your system?

**Comment by wow6haka** [comment]
很无奈，似乎只有win7系统自带的图片查看器有问题，在其他电脑软件上、手机上均正常显示。我搜索到一个方法，删除掉jpg的icc信息，即可正常显示。我猜测这可能是win7照片查看器的bug。。

**Comment by neocotic** [comment]
Closing as I haven't heard anything for a while and last comment suggests it's a Windows 7 bug.
