### ISSUE TITLE
Arabic characters displayed properly with small svg but not with large one  

### ISSUE THREAD

**Issue by rahman-a** [neocotic/convert-svg#73]
when  I try to convert small SVG with Arabic names the library doing great job but when it comes to large SVG full of Arabic names I start to see weird characters instead of Arabic ones 
instead of seeing Arabic name like that  (أحمد) I see that  (ÙØ§Ø·Ù…Ø©)

**Comment by neocotic** [comment]
I'm sorry for the incredibly long delay in replying in responding to you but life sometimes gets in the way of OSS development. I thank you for your patience and, although I'm closing this issue out, I hope you'll be glad to know that I believe this issue has been resolved in with today's [0.6.0](https://github.com/neocotic/convert-svg/releases/tag/0.6.0) release with the introduction of UTF-8 support.

If you continue to have this problem, please raise a new ticket with an SVG to reproduce the problem and, where possible, an expected and actual file of the output. I hope you can understand my delay.
