### ISSUE TITLE
Puppeteer options setup through CLI won't apply!

### ISSUE THREAD

**Issue by IskandarAlex2** [neocotic/convert-svg#99]
I have a Docker Container that uses [convert-svg-to-png](https://github.com/neocotic/convert-svg/tree/main/packages/convert-svg-to-png), the issue is that this package doesn't put options to the Puppeteer.launch() which since the Docker Container is running in `/root`, Puppeteer errors with `Running as root without --no-sandbox is not supported` I saw pull request #29 which mention this issue especially so I add `RUN apt-get update && npm install -g convert-svg-to-png && npm install --save convert-svg-to-png` and `RUN convert-svg-to-png --puppeteer='{ "headless": true, "args": ["--no-sandbox"] }' *.svg` into my Dockerfile, but yet **It still errors with a same exact error when trying to use the converting module**, Puppeteer itself works in the Docker Container and I even tried raw of it, the reason I use this package is that when I use raw puppeteer it seems to render the SVG wrongly like having a weird white outline on the left and this package seems to solve that issue somehow, a fix for neither of those can help.

**Comment by b1n1yam** [comment]
+1
